Remaniement et introduction de la notion de `PieceJointe` dans `Entete`
betagouv/oots-france pull request #70
Opened 2024-03-05 10:57 UTC by Fabinout

2024-03-05 10:59 UTC, Fabinout commented on src/ebms/entete.js
> +        <eb:Property name="MimeType">application/x-ebrs+xml</eb:Property>
Problème d'indentation

2024-03-05 11:00 UTC, Fabinout commented on src/ebms/entete.js
> +
saut de ligne en trop

2024-03-05 13:30 UTC, egaillot commented
Vu ensemble : il reste à utiliser cet objet métier dans la génération du corps du message.

2024-03-11 17:18 UTC, egaillot commented on test/domibus/requete.spec.js
> +      expect(reponse.pieceJointe.contenuPieceJointe).toBeDefined();
Cf. commentaire ci-dessus.

Est-ce que ça aurait du sens d'écrire ce qui suit ?…
```javascript
expect(reponse.idPieceJointe()).toBe('…');
```
… Peut-être pas en fait 🤔 Je m'attends à ce qu'on passe à un moment de `reponse.pieceJointe` à `reponse.piecesJointes` (une réponse pouvant avoir plusieurs pièces jointes). Des idées ?

2024-03-12 09:29 UTC, Fabinout commented on test/domibus/requete.spec.js
> +      expect(reponseErreur.pieceJointe.contenuPieceJointe).toBeUndefined();
piecejointe.constructor.name === 'PieceJointe'

2024-03-18 13:14 UTC, egaillot commented on src/ebms/message.js
> +      ${PieceJointeVide.enXMLDansCorps()}
Ça devrait être `this.pieceJointe` je pense.

2024-04-02 08:56 UTC, egaillot requested changes

2024-04-02 08:56 UTC, egaillot commented on src/ebms/pieceJointe.js
> +  enXMLDansMessage() {
Le nom n'est pas cohérent avec celui utilisé dans `PieceJointeVide`.

2024-04-02 09:00 UTC, egaillot commented on src/ebms/message.js
> +  pieceJointePresente = () => this.pieceJointe.constructor.name === 'PieceJointe';
Pour une autre PR peut-être : plutôt faire un appel du style `this.pieceJointe.presente()`

2024-04-02 12:14 UTC, egaillot approved these changes
👍

2024-04-02 12:19 UTC, egaillot commented on src/ebms/entete.js
> +    this.pieceJointe = donnees.pieceJointe || new PieceJointeVide();
On devrait pouvoir se passer de cette initialisation, vu que ce constructeur est appelé depuis `Message`, où l'initialisation est déjà faite.

2024-04-02 12:43 UTC, merged