Déplacement du code de la page d'accueil dans un moteur de template
betagouv/oots-france pull request #85
Opened 2024-04-12 11:07 UTC by Fabinout

2024-04-15 09:28 UTC, egaillot requested changes
J'aime l'idée d'être autonome et ne pas dépendre d'une bibliothèque tierce ici… mais je me demande si finalement ça ne serait pas un compromis acceptable de passer par `express-mustache` qui nous inviterait à utiliser des standards d'API et de syntaxe, pour une dépendance limitée à 3 modules.

2024-04-15 09:28 UTC, egaillot commented on src/views/modelePageAccueil.js
> +                <a href="/auth/fcplus/destructionSession">Déconnexion</a>`,
C'est dommage que le modèle connaisse du HTML, qui induit un un couplage avec la vue. Cela vient du fait qu'on n'ait pas de structure conditionnelle dans la vue vierge.

Peut-être que c'est un trop gros pas pour cette PR, et qu'on peut vivre avec ça pour l'instant.

2024-04-15 09:28 UTC, egaillot commented on src/views/modelePageAccueil.js
> +      '{{contenu}}',
La duplication ici est dommage. Ça pourrait valoir le coup de la résoudre dès maintenant, par exemple en remontant ce bout de code dans `enHTML`.

2024-04-15 09:28 UTC, egaillot commented on test/views/modelePageAccueil.spec.js
> +  it("affiche les prénom et nom de l'utilisatrice courant si elle est connectée", () => {
Typo : courante (au féminin)

2024-04-15 09:28 UTC, egaillot commented on test/routes/routesBase.spec.js
> -    });
Je suis embêté qu'on supprime ce test, qui parle de l'injection des infos de l'utilisateur courant depuis le middleware. J'aimerais qu'on le conserve. La duplication du test avec `ModelePageAccueil` vient du fait qu'on injecte une dépendance `new ModelePageAccueil` depuis la route. Cela plaide en faveur de l'utilisation d'un `reponse.render(…)` qui nous permettrait de mocker les choses et s'assurer de l'injection des infos depuis le middleware sans avoir à tester le contenu de la vue.

2024-04-15 09:28 UTC, egaillot commented on src/views/modelePageAccueil.js
> +      `<p>Utilisateur courant : ${this.infosUtilisateur.given_name} ${this.infosUtilisateur.family_name}</p>
On ne garantit pas que `this.infosUtilisateur` contient un attribut `given_name` ou `famiily_name`. On risque ici de se retrouver avec une erreur, dont on pourrait se prémunir (par exemple, en écrivant `this.infosUtilisateur?.given_name` ou en ajoutant un `catch` dans la route).

2024-04-29 09:09 UTC, egaillot commented on src/routes/routesBase.js
> +const ModelePageAccueil = require('../views/modelePageAccueil');
Le fait de traduire _template_ par _modèle_ entraîne une confusion avec le terme _model_ qui renvoie au concept de MVC. Par ailleurs, autant utiliser _vues_ plutôt que _vues_.

Je suggère ainsi qu'on écrive

```javascript
const PageAccueil = require('../vues/pageAccueil');
```

2024-04-29 09:10 UTC, egaillot commented on src/views/modelePageAccueil.js
> +                <a href="/auth/fcplus/destructionSession">Déconnexion</a>`,
Vu ensemble – ce n'est finalement pas un modèle au sens MVC, mais un modèle au sens _template_.

2024-04-29 09:17 UTC, egaillot commented on src/views/pageAccueil.html
> +{{contenu}}
Quitte à utiliser la syntaxe mustache, on pourrait avoir directement dans le template un truc du style

```html
<body>
{{#infosUtilisateur}}
  <p>{{given_name}} {{family_name}}</p>
  <a href='…'>Se déconnecter</a>
{{/contenu}}
{{^infosUtilisateur}}
  <p>Pas d'utilisateur courant</p>
{{/contenu}}
</body>
```

2024-04-29 09:29 UTC, egaillot commented on src/views/modelePageAccueil.js
> +      `<p>Utilisateur courant : ${this.infosUtilisateur.given_name} ${this.infosUtilisateur.family_name}</p>
Vu ensemble – en fait, cette méthode n'est appelée que s'il y a des `infosUtilisateur` (cf. ligne 11). Éventuellement, mettre une sentinelle, mais c'est peut-être overkill.

2024-04-30 08:53 UTC, Fabinout commented
Remplacée par #89

2024-04-30 08:53 UTC, closed without merging